### PR TITLE
Fix property wrapper initialization order in two view inits

### PR DESCRIPTION
**Pull request by thboehi**
`AuthorizationView` and `ComposeToolbar` both fail to build with Xcode 27 (Swift 6.2):

```
AuthorizationView.swift:26:13: error: variable 'self.authConfig' used before being initialized
ComposeToolbar.swift:19:9: error: variable 'self.keyboardShown' used before being initialized
```

### Cause

Both inits assign to `@State` properties that declare a default value:

```swift
@State private var password: String = ""
@State private var linkText: String = ""
```

Because the wrapper storage is already initialized by that default, `self.password = password` is a *setter call through the property wrapper* rather than an initialization, and so counts as a use of `self`. Definite initialization then requires every stored property to be initialized first, and the `@Binding` properties, which have no default, were only assigned further down the init.

Xcode 26 accepted this; Xcode 27 rejects it.

### Change

Move the binding assignments above the affected writes in both inits. The reordered statements have no dependencies between them, so behaviour is unchanged. `swift-format lint` passes on both files.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by asoucar** [comment]
Thank you for your interest in the project. We are not currently accepting community contributions, especially AI contributions, at this time.
